sudo: required
services:
  - docker

# Build the test image
before_install:
  - docker build -t sankarmuthaiah/mutli-docker-test -f ./client/Dockerfile.dev ./client

# Run the tests in test image
script:
  - docker run -e CI=true sankarmuthaiah/mutli-docker-test npm run test

# Build the production images and push to docker-hub
after_success:
  # Build the production images
  - docker build -t sankarmuthaiah/multi-docker-client ./client
  - docker build -t sankarmuthaiah/multi-docker-nginx ./nginx
  - docker build -t sankarmuthaiah/multi-docker-server ./server
  - docker build -t sankarmuthaiah/multi-docker-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the production images to docker-hub
  - docker push sankarmuthaiah/multi-docker-client
  - docker push sankarmuthaiah/multi-docker-nginx
  - docker push sankarmuthaiah/multi-docker-server
  - docker push sankarmuthaiah/multi-docker-worker
