sudo: required
services:
  - docker

# Build the test image
before_install:
  - docker build -t whizzler/mutli-docker-test -f ./client/Dockerfile.dev ./client

# Run the tests in test image
script:
  - docker run -e CI=true whizzler/mutli-docker-test npm run test

# Build the production images and push to docker-hub
after_success:
  # Build the production images
  - dockber build -t whizzler/multi-docker-client ./client
  - dockber build -t whizzler/multi-docker-nginx ./nginx
  - dockber build -t whizzler/multi-docker-server ./server
  - dockber build -t whizzler/multi-docker-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the production images to docker-hub
  - docker push whizzler/multi-docker-client
  - docker push whizzler/multi-docker-nginx
  - docker push whizzler/multi-docker-server
  - docker push whizzler/multi-docker-worker
